### PR TITLE
added diff-cover level exclude files (some func taken from flake8)

### LINKED ISSUE #65: add an option to exclude files
The problem is with pylint, diif_cover launches pylint with a given changed file, but pylint ignore does not work in that case.

e.g.
- there's a change in data/folder/dontwantthat.py
- pylint.rc has
ignore=CVS,folder

pylint still checks the file

### PR DESCRIPTION
**Pull request by agroszer**
closes #65

### CODE REVIEW

**Comment by Bachmann1234** [comment]
ugh oh. Hmm looks like the pep8 to pycode style transition is breaking these tests. Probably failing on master as well. I need to try to look into this sometime soon. May be trickey this week but ill make an effort

**Comment by Bachmann1234** [comment]
Opened https://github.com/Bachmann1234/diff-cover/pull/67 to address the pycodestyle errors

**Comment by Bachmann1234** [comment]
Ok, master is healthy again. If you rebase your branch this build should turn green

**Comment by agroszer** [comment]
cool thanks!

**Comment by Bachmann1234** [comment]
Released! Went ahead and made this 1.0 since I made some backwards incompatible changes https://pypi.python.org/pypi/diff_cover/1.0.0

**Pull request merged**
