### PR TITLE
added ESLint driver

### PR DESCRIPTION
**Pull request by agroszer**

### CODE REVIEW

**Comment by Bachmann1234** [comment]
Overal looks pretty good. 

Remove that last commit though. Upgrading pygments is a separate task.

One note. Master has not been released yet as I am waiting on @benpatterson to at least try out master against their stuff since it is a lot of refactoring of the currently released version. So it may take a bit.

**Comment by agroszer** [comment]
last commit: yeah, bloody github added it from the fork without asking...

**Comment by agroszer** [comment]
release is not a concern, we can use the fork

**Comment by agroszer** [comment]
please merge I need to set that pin back for us to work

**Comment by benpatterson** [comment]
Haven't forgotten to get a closer look at master, @Bachmann1234 . But clearly things are moving a bit slow...so I will put it into our next sprint (which starts in 2 weeks) so we can be sure to get that done.

**Comment by Bachmann1234** [comment]
This is released! https://pypi.python.org/pypi/diff_cover/0.9.0 Thanks @benpatterson for taking a look

**Comment by Bachmann1234** [comment]
@agroszer  Thanks again for the PR!

**Pull request merged**
