### PR TITLE
Fix command line tools for Windows

### PR DESCRIPTION
**Pull request by evanunderscore**
Fix regression for issue #17

### CODE REVIEW

**Comment by Bachmann1234** [comment]
Hero! I'll look over this either tonight or tomorrow. If you are not already you should add yourself to the authors file!

**Comment by Bachmann1234** [comment]
Merging, Feel free to open a PR to add yourself to authors. Ill merge it. Or just let me know here and ill add it myself :-)

**Comment by Bachmann1234** [comment]
Thanks again. Released https://pypi.python.org/pypi/diff_cover/0.8.6

**Comment by evanunderscore** [comment]
Thanks. If I end up making another contribution I'll just add myself to authors then.

**Comment by Bachmann1234** [comment]
:-)

**Pull request merged**
