### PR TITLE
[WIP] Plugins

### PR DESCRIPTION
**Pull request by Bachmann1234**
This is the PR that will serve as the start of diff-qualities plugin system.

This is currently a work in progress.

### CODE REVIEW

**Comment by Bachmann1234** [comment]
Basically so far I have revamped how diff-quality works.

Now there is a single reporter that takes in a driver. This driver is to be the basis for plugins. If all goes well people will be able to write their own drivers and diff-quality can pick them up and treat them like any other reporter.

**Comment by Bachmann1234** [comment]
Todo:  A bit more moving stuff around, and integrating stevedore

**Comment by Bachmann1234** [comment]
Merging the WIP but not releasing. Code passes the tests and I dont want any issues if someone tries to open a PR. Hopefully Ill be able to Finish Stevedore integration soon

**Comment by faulkner** [comment]
@Bachmann1234 nice!  Not sure if you're already aware, but it looks like the command is only ran against the first file it finds in `diff-quality` now due to these changes (I came across this while trying to debug an issue with how moved files are handled, which appear to not work properly both in the current release as well as this version).  I've only tested it against the current version of pylint, but since `command_runner.execute()` only gets called on the first file the rest get flagged as 100%.

**Comment by Bachmann1234** [comment]
@faulkner Oh jeez. Good thing I have not released this. Thanks for the heads up. Clearly have some gaps in my test suite :-(

**Comment by Bachmann1234** [comment]
Oh wow, not working in the released version? Thats really bad. Ill try and look into this tonight

**Comment by faulkner** [comment]
@Bachmann1234 I was just noticing that pylint would return things like `Could not load 'filename_before_move.py'` that weren't bubbling up to the report or being handled in some other way, but it's running against the new files just fine, so that particular issue may not be anything to worry about.

**Comment by Bachmann1234** [comment]
Phew

**Comment by Bachmann1234** [comment]
@faulkner pylint continues to be a problem for me. We could have diff-quality log or add to the report any warnings. But quite frankly its low on my priority list right now. Starting a new job and all so time is tight. I would like to finish up the plugin stuff soon and handle any issues that come in but its hard to promise much.

**Pull request merged**
