### PR TITLE
add pydocstyle support

### PR DESCRIPTION
**Pull request by mr-c**
Closes https://github.com/Bachmann1234/diff-cover/issues/52

### CODE REVIEW

**Comment by Bachmann1234** [comment]
Awesome! Thanks for the PR. 

Only issue is this needs some tests. There should be a bunch of examples in the code

**Comment by Bachmann1234** [comment]
Looks like python 2.6 is not working quite right. Not 100% clear why. Ill see if I can find some time to look into this

**Comment by lyndsysimon** [comment]
It looks like [pydocstyle doesn't support 2.6](http://www.pydocstyle.org/en/latest/#pydocstyle-s-documentation). The failing test for 2.6 is happening because `pydocstyle --version` returns the following traceback under 2.6:

```
Traceback (most recent call last):
  File "/Users/lyndsy.simon/src/pypi/diff-cover/.tox/py26/bin/pydocstyle", line 7, in <module>
    from pydocstyle.cli import main
  File "/Users/lyndsy.simon/src/pypi/diff-cover/.tox/py26/lib/python2.6/site-packages/pydocstyle/__init__.py", line 1, in <module>
    from .checker import check
  File "/Users/lyndsy.simon/src/pypi/diff-cover/.tox/py26/lib/python2.6/site-packages/pydocstyle/checker.py", line 11, in <module>
    from . import violations
  File "/Users/lyndsy.simon/src/pypi/diff-cover/.tox/py26/lib/python2.6/site-packages/pydocstyle/violations.py", line 242
    'pep257': all_errors - {'D203', 'D212', 'D213', 'D214', 'D215', 'D404',
                                  ^
SyntaxError: invalid syntax
```

**Comment by Bachmann1234** [comment]
Ah. That makes sense. Good on them.

But for our purposes I think all that's needed is a better error message. "Pydocstyle does not support python 2.6" 

If the build is still complaining about coverage after that I'll work around it

**Comment by mr-c** [comment]
I think this is ready for merging, thanks!

I made an issue to provide a better user experience with `pydocstyle` and Python 2.6: https://github.com/PyCQA/pydocstyle/issues/271

**Comment by Bachmann1234** [comment]
Yep! I'll merge and do a release sometime this weekend or early next week (Monday at the latest )

**Comment by Bachmann1234** [comment]
Thanks!

**Comment by Bachmann1234** [comment]
Released! Thanks https://pypi.python.org/pypi/diff_cover/0.9.12

**Pull request merged**
